# Generated by Django 3.0.14 on 2024-03-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Post',
        ),
    ]
