# Generated by Django 3.0.14 on 2024-03-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
